name: DiscordLink
version: ${project.version}
main: cz.bloodbear.discordLink.paper.DiscordLink
api-version: 1.20

author: Mtn16
description: Seamless Discord Integration for Velocity and Paper
website: https://github.com/Mtn16/DiscordLink
depend: [LuckPerms]
softdepend: [PlaceholderAPI]

commands:
  discordadmin:
    description: DiscordLink admin command
    usage: /discordadmin <resync|resyncAll> [player]
    permission: discordlink.admin
  discord:
    description: DiscordLink admin command
    usage: /discord [link|unlink|info]

permissions:
  discordlink.player:
    default: notop
    children:
      discordlink.player.link: true
      discordlink.player.unlink: true
      discordlink.player.info: true

  discordlink.admin:
    default: op
    children:
      discordlink.admin.reload: true
      discordlink.admin.resync: true
      discordlink.admin.resyncall: true
