name: DiscordLink
version: ${project.version}
main: cz.bloodbear.discordLink.paper.DiscordLink
api-version: 1.20

author: Mtn16
description: Seamless Discord Integration for Velocity and Paper
website: https://github.com/Mtn16/DiscordLink
depend: [LuckPerms]
softdepend: [PlaceholderAPI]

commands:
  discordadmin:
    description: DiscordLink admin command
    usage: /discordadmin <resync|resyncAll> [player]
    permission: discordlink.admin
  discord:
    description: DiscordLink admin command
    usage: /discord [link|unlink|info]

permissions:
  discordlink.player:
    default: notop
  discordlink.player.link:
    default: notop
  discordlink.player.unlink:
    default: notop
  discordlink.player.info:
    default: notop

  discordlink.admin:
    default: op
  discordlink.admin.reload:
    default: op
  discordlink.admin.resync:
    default: op
  discordlink.admin.resyncall:
    default: op
